# Generated by Django 5.0.7 on 2024-08-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myrdal_api", "0002_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payee", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("shopping", "Shopping"),
                            ("travel", "Travel"),
                            ("healthcare", "Healthcare"),
                            ("entertainment", "Entertainment"),
                            ("utilities", "Utilities"),
                            ("education", "Education"),
                            ("gifts_donations", "Gifts/Donations"),
                            ("unspecified", ""),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myrdal_api.account",
                    ),
                ),
            ],
        ),
    ]
