name: Static analysis

on:
  # Triggers the workflow on push or pull request events for all branches
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  frontend_linting:
    name: Run frontend linting tools
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Open frontend directory
        run: cd frontend

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          stylelint: true
  
  backend_linting:
    name: Run backend linting tools
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Open backend directory
        run: cd backend

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install black pylint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true

  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04

    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "frontend/src/, backend/myrdal_api"