name: Static analysis

on:
  # Triggers the workflow on push or pull request events for thedev and main branches
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:

jobs:
  frontend_linting:
    name: Run frontend linting tools
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: 'frontend'

      - name: Run stylelint with reviewdog
        uses: reviewdog/action-stylelint@v1.22.1
        with:
          reporter: github-pr-review
          stylelint_input: "**/*.css"
          workdir: 'frontend'
  
  backend_linting:
    name: Run backend linting tools
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Open backend directory
        run: cd backend

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install black pylint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true

  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04

    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          directories: "frontend/src/, backend/myrdal_api"
        if: github.event_name == 'pull_request'
