name: Test

on:
  # Triggers the workflow after static analysis is completed.
  workflow_run:
    workflows: [Static analysis]
    types:
      - completed

jobs:
  frontend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run Tests'
        run: npx vitest --coverage.enabled true

      - name: 'Display Vitest Coverage Report'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.5.0
        with:
          working-directory: 'frontend'

  backend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend'
    
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 'Set up Python 3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install Dependencies'
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: 'Run Tests'
        run: |
            coverage run --branch manage.py test
            coverage xml

      - name: 'Display coverage report'
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
